name: Python Script Workflow

on:
  push:
    branches:
      - master       # Run on every push to main branch
  schedule:
    - cron: '2 19 * * *'  # Optional: Schedule to run daily

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_ID: "@bugin_ne_kun"  # Directly set the channel ID here

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  

    - name: Run Python script
      run: python pytgbot.py
